/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://6iqyjmnntbggxl5i4yfw6437bu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b5fdvo3xfrbsbmd3yqs6656znu",
    "aws_cognito_identity_pool_id": "eu-west-1:9b77b096-d30a-4481-84e8-c997074f0088",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_0IOey4eM6",
    "aws_user_pools_web_client_id": "47afcoa949qq6fmb323nriusov",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "datacollectiond668c108905d468c8df20ddb788a872a8bc8a-datacol",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
